---
name: Create release and package

on:
  push:
    branches:
      - main

jobs:
  create-release-and-package:
    uses: rahulsalvi/.github/.github/workflows/create-release-and-package.yaml@main
    with:
      image_name: ${{ github.repository }}
    secrets: inherit
