---
name: Create release and package

on:
  push:
    branches:
      - main

jobs:
  create-release-and-package:
    uses: rahulsalvi/.github/.github/workflows/create-release-and-package.yaml@main
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
      artifact-metadata: write
    secrets: inherit
